-- ============================================
-- Users Service - Device Token Management
-- Table: USR_DEVICE_TOKENS
-- Description: Store FCM device tokens for push notifications
-- ============================================

-- Drop table if exists (for clean reinstall)
-- DROP TABLE USR_DEVICE_TOKENS CASCADE CONSTRAINTS;

-- Create device tokens table
CREATE TABLE USR_DEVICE_TOKENS (
    ID VARCHAR2(36) PRIMARY KEY,
    USER_ID VARCHAR2(36) NOT NULL,
    EMPLOYEE_CODE VARCHAR2(50),
    DEVICE_TOKEN VARCHAR2(500) NOT NULL,
    DEVICE_TYPE VARCHAR2(20), -- 'ios', 'android', 'web'
    DEVICE_NAME VARCHAR2(100), -- 'iPhone 13', 'Samsung Galaxy S21'
    DEVICE_OS_VERSION VARCHAR2(50), -- 'iOS 16.0', 'Android 13'
    APP_VERSION VARCHAR2(20), -- '1.0.0'
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP,
    VERSION NUMBER DEFAULT 1,
    CREATED_BY VARCHAR2(36),
    UPDATED_BY VARCHAR2(36),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    LAST_USED_AT TIMESTAMP,
    
    CONSTRAINT FK_DEVICE_USER FOREIGN KEY (USER_ID) REFERENCES USR_USERS(ID) ON DELETE CASCADE,
    CONSTRAINT UQ_DEVICE_TOKEN UNIQUE (DEVICE_TOKEN),
    CONSTRAINT CHK_DEVICE_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- Create indexes for better query performance
CREATE INDEX IDX_DEVICE_USER ON USR_DEVICE_TOKENS(USER_ID);
CREATE INDEX IDX_DEVICE_EMPLOYEE ON USR_DEVICE_TOKENS(EMPLOYEE_CODE);
CREATE INDEX IDX_DEVICE_ACTIVE ON USR_DEVICE_TOKENS(IS_ACTIVE);
CREATE INDEX IDX_DEVICE_LAST_USED ON USR_DEVICE_TOKENS(LAST_USED_AT);

-- Create composite index for common queries
CREATE INDEX IDX_DEVICE_EMP_ACTIVE ON USR_DEVICE_TOKENS(EMPLOYEE_CODE, IS_ACTIVE);

-- Add comments
COMMENT ON TABLE USR_DEVICE_TOKENS IS 'Device tokens for push notifications (FCM)';
COMMENT ON COLUMN USR_DEVICE_TOKENS.ID IS 'Primary key (UUID)';
COMMENT ON COLUMN USR_DEVICE_TOKENS.USER_ID IS 'Foreign key to USR_USERS';
COMMENT ON COLUMN USR_DEVICE_TOKENS.EMPLOYEE_CODE IS 'Employee code for quick lookup';
COMMENT ON COLUMN USR_DEVICE_TOKENS.DEVICE_TOKEN IS 'FCM device token (unique)';
COMMENT ON COLUMN USR_DEVICE_TOKENS.DEVICE_TYPE IS 'Device platform: ios, android, web';
COMMENT ON COLUMN USR_DEVICE_TOKENS.DEVICE_NAME IS 'Device model name';
COMMENT ON COLUMN USR_DEVICE_TOKENS.DEVICE_OS_VERSION IS 'Operating system version';
COMMENT ON COLUMN USR_DEVICE_TOKENS.APP_VERSION IS 'Mobile app version';
COMMENT ON COLUMN USR_DEVICE_TOKENS.IS_ACTIVE IS '1=active, 0=inactive';
COMMENT ON COLUMN USR_DEVICE_TOKENS.LAST_USED_AT IS 'Last time this token was used';

-- Grant permissions (adjust as needed)
-- GRANT SELECT, INSERT, UPDATE ON USR_DEVICE_TOKENS TO your_app_user;
