-- Migration: Add HIS Employee fields to USR_USER_PROFILES table
-- Date: 2025-12-12
-- Description: Add fields from HIS_EMPLOYEE table to UserProfile entity

-- HIS Employee fields - Thông tin nghề nghiệp
ALTER TABLE USR_USER_PROFILES ADD (
  DIPLOMA VARCHAR2(255),
  IS_DOCTOR NUMBER(1,0) DEFAULT 0,
  IS_NURSE NUMBER(1,0) DEFAULT 0,
  TITLE VARCHAR2(255),
  CAREER_TITLE_ID NUMBER(19,0)
);

-- HIS Employee fields - Thông tin tổ chức
ALTER TABLE USR_USER_PROFILES ADD (
  DEPARTMENT_ID NUMBER(19,0),
  BRANCH_ID NUMBER(19,0),
  DEFAULT_MEDI_STOCK_IDS VARCHAR2(1000)
);

-- HIS Employee fields - Thông tin cá nhân
ALTER TABLE USR_USER_PROFILES ADD (
  GENDER_ID NUMBER(19,0),
  ETHNIC_CODE VARCHAR2(50),
  IDENTIFICATION_NUMBER VARCHAR2(50),
  SOCIAL_INSURANCE_NUMBER VARCHAR2(50)
);

-- HIS Employee fields - Bằng cấp
ALTER TABLE USR_USER_PROFILES ADD (
  DIPLOMA_DATE DATE,
  DIPLOMA_PLACE VARCHAR2(500)
);

-- HIS Employee fields - Cấu hình
ALTER TABLE USR_USER_PROFILES ADD (
  MAX_SERVICE_REQ_PER_DAY NUMBER(10,0),
  DO_NOT_ALLOW_SIMULTANEITY NUMBER(1,0) DEFAULT 0,
  IS_ADMIN NUMBER(1,0) DEFAULT 0
);

-- Add comments for documentation
COMMENT ON COLUMN USR_USER_PROFILES.DIPLOMA IS 'Diploma/Certificate';
COMMENT ON COLUMN USR_USER_PROFILES.IS_DOCTOR IS 'Is Doctor (0/1)';
COMMENT ON COLUMN USR_USER_PROFILES.IS_NURSE IS 'Is Nurse (0/1)';
COMMENT ON COLUMN USR_USER_PROFILES.TITLE IS 'Job Title';
COMMENT ON COLUMN USR_USER_PROFILES.CAREER_TITLE_ID IS 'Career Title ID';
COMMENT ON COLUMN USR_USER_PROFILES.DEPARTMENT_ID IS 'Department ID';
COMMENT ON COLUMN USR_USER_PROFILES.BRANCH_ID IS 'Branch ID';
COMMENT ON COLUMN USR_USER_PROFILES.DEFAULT_MEDI_STOCK_IDS IS 'Default Medical Stock IDs (JSON string)';
COMMENT ON COLUMN USR_USER_PROFILES.GENDER_ID IS 'Gender ID';
COMMENT ON COLUMN USR_USER_PROFILES.ETHNIC_CODE IS 'Ethnic Code';
COMMENT ON COLUMN USR_USER_PROFILES.IDENTIFICATION_NUMBER IS 'Identification Number (CMND/CCCD)';
COMMENT ON COLUMN USR_USER_PROFILES.SOCIAL_INSURANCE_NUMBER IS 'Social Insurance Number';
COMMENT ON COLUMN USR_USER_PROFILES.DIPLOMA_DATE IS 'Diploma Date';
COMMENT ON COLUMN USR_USER_PROFILES.DIPLOMA_PLACE IS 'Diploma Place';
COMMENT ON COLUMN USR_USER_PROFILES.MAX_SERVICE_REQ_PER_DAY IS 'Max Service Requests Per Day';
COMMENT ON COLUMN USR_USER_PROFILES.DO_NOT_ALLOW_SIMULTANEITY IS 'Do Not Allow Simultaneity (0/1)';
COMMENT ON COLUMN USR_USER_PROFILES.IS_ADMIN IS 'Is Admin (0/1)';

