-- Add Actual Export fields to EXP_INP_EXP_MEST_MED table
ALTER TABLE EXP_INP_EXP_MEST_MED 
ADD (
  ACTUAL_EXP_AMOUNT NUMBER(18,2) NULL,
  ACTUAL_EXP_BY_USER VARCHAR2(36) NULL,
  ACTUAL_EXP_TIME NUMBER(19,0) NULL
);

COMMENT ON COLUMN EXP_INP_EXP_MEST_MED.ACTUAL_EXP_AMOUNT IS 'Actual export amount (Thực xuất)';
COMMENT ON COLUMN EXP_INP_EXP_MEST_MED.ACTUAL_EXP_BY_USER IS 'User ID who actually exported (UUID)';
COMMENT ON COLUMN EXP_INP_EXP_MEST_MED.ACTUAL_EXP_TIME IS 'Actual export time (YYYYMMDDHHMMSS)';

