-- Create EXP_EXP_MEST_OTHER table (Parent records from GetView2)
CREATE TABLE EXP_EXP_MEST_OTHER (
  ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  CREATE_TIME NUMBER(19,0) NOT NULL,
  MODIFY_TIME NUMBER(19,0) NOT NULL,
  CREATOR VARCHAR2(100) NULL,
  MODIFIER VARCHAR2(100) NULL,
  IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
  IS_DELETE NUMBER(1,0) DEFAULT 0 NOT NULL,
  
  -- Primary Key từ HIS
  HIS_EXP_MEST_ID NUMBER(19,0) NOT NULL UNIQUE,
  
  -- Basic Info
  EXP_MEST_CODE VARCHAR2(50) NULL,
  EXP_MEST_TYPE_ID NUMBER(19,0) NULL,
  EXP_MEST_STT_ID NUMBER(19,0) NULL,
  MEDI_STOCK_ID NUMBER(19,0) NULL,
  
  -- Request Info
  REQ_LOGINNAME VARCHAR2(100) NULL,
  REQ_USERNAME VARCHAR2(500) NULL,
  REQ_ROOM_ID NUMBER(19,0) NULL,
  REQ_DEPARTMENT_ID NUMBER(19,0) NULL,
  CREATE_DATE NUMBER(18,0) NULL,
  REQ_USER_TITLE VARCHAR2(200) NULL,
  
  -- Service Request Info
  SERVICE_REQ_ID NUMBER(19,0) NULL,
  TDL_TOTAL_PRICE NUMBER(18,2) NULL,
  TDL_SERVICE_REQ_CODE VARCHAR2(50) NULL,
  TDL_INTRUCTION_TIME NUMBER(18,0) NULL,
  TDL_INTRUCTION_DATE NUMBER(18,0) NULL,
  TDL_INTRUCTION_DATE_MIN NUMBER(18,0) NULL,
  
  -- Treatment Info
  TDL_TREATMENT_ID NUMBER(19,0) NULL,
  TDL_TREATMENT_CODE VARCHAR2(50) NULL,
  
  -- Patient Info
  TDL_PATIENT_ID NUMBER(19,0) NULL,
  TDL_PATIENT_CODE VARCHAR2(50) NULL,
  TDL_PATIENT_NAME VARCHAR2(500) NULL,
  TDL_PATIENT_FIRST_NAME VARCHAR2(200) NULL,
  TDL_PATIENT_LAST_NAME VARCHAR2(200) NULL,
  TDL_PATIENT_DOB NUMBER(18,0) NULL,
  TDL_PATIENT_IS_HAS_NOT_DAY_DOB NUMBER(1,0) NULL,
  TDL_PATIENT_ADDRESS VARCHAR2(1000) NULL,
  TDL_PATIENT_GENDER_ID NUMBER(19,0) NULL,
  TDL_PATIENT_GENDER_NAME VARCHAR2(100) NULL,
  TDL_PATIENT_TYPE_ID NUMBER(19,0) NULL,
  TDL_HEIN_CARD_NUMBER VARCHAR2(50) NULL,
  TDL_PATIENT_PHONE VARCHAR2(50) NULL,
  TDL_PATIENT_PROVINCE_CODE VARCHAR2(10) NULL,
  TDL_PATIENT_DISTRICT_CODE VARCHAR2(10) NULL,
  TDL_PATIENT_COMMUNE_CODE VARCHAR2(10) NULL,
  TDL_PATIENT_NATIONAL_NAME VARCHAR2(200) NULL,
  
  -- Virtual Fields
  VIR_CREATE_MONTH NUMBER(18,0) NULL,
  VIR_CREATE_YEAR NUMBER(10,0) NULL,
  VIR_HEIN_CARD_PREFIX VARCHAR2(10) NULL,
  
  -- ICD Info
  ICD_CODE VARCHAR2(50) NULL,
  ICD_NAME VARCHAR2(1000) NULL,
  ICD_SUB_CODE VARCHAR2(500) NULL,
  ICD_TEXT VARCHAR2(2000) NULL,
  
  -- Denormalized Type/Status/Stock Info
  EXP_MEST_TYPE_CODE VARCHAR2(10) NULL,
  EXP_MEST_TYPE_NAME VARCHAR2(500) NULL,
  EXP_MEST_STT_CODE VARCHAR2(10) NULL,
  EXP_MEST_STT_NAME VARCHAR2(500) NULL,
  MEDI_STOCK_CODE VARCHAR2(50) NULL,
  MEDI_STOCK_NAME VARCHAR2(500) NULL,
  REQ_DEPARTMENT_CODE VARCHAR2(50) NULL,
  REQ_DEPARTMENT_NAME VARCHAR2(500) NULL,
  REQ_ROOM_CODE VARCHAR2(50) NULL,
  REQ_ROOM_NAME VARCHAR2(500) NULL,
  
  -- Aggregated Codes
  TDL_AGGR_PATIENT_CODE VARCHAR2(4000) NULL,
  TDL_AGGR_TREATMENT_CODE VARCHAR2(4000) NULL,
  
  -- Other Fields
  EXP_MEST_SUB_CODE VARCHAR2(50) NULL,
  EXP_MEST_SUB_CODE_2 VARCHAR2(100) NULL,
  NUM_ORDER NUMBER(10,0) NULL,
  PRIORITY NUMBER(10,0) NULL,
  GROUP_CODE VARCHAR2(50) NULL,
  PATIENT_TYPE_CODE VARCHAR2(10) NULL,
  PATIENT_TYPE_NAME VARCHAR2(200) NULL,
  TREATMENT_IS_ACTIVE NUMBER(1,0) NULL,
  
  -- Last Export/Approval Info
  LAST_EXP_LOGINNAME VARCHAR2(100) NULL,
  LAST_EXP_USERNAME VARCHAR2(500) NULL,
  LAST_EXP_TIME NUMBER(18,0) NULL,
  FINISH_TIME NUMBER(18,0) NULL,
  FINISH_DATE NUMBER(18,0) NULL,
  IS_EXPORT_EQUAL_APPROVE NUMBER(1,0) NULL,
  LAST_APPROVAL_LOGINNAME VARCHAR2(100) NULL,
  LAST_APPROVAL_USERNAME VARCHAR2(500) NULL,
  LAST_APPROVAL_TIME NUMBER(18,0) NULL,
  LAST_APPROVAL_DATE NUMBER(18,0) NULL,
  
  -- HIS Timestamps
  HIS_CREATE_TIME NUMBER(18,0) NULL,
  HIS_MODIFY_TIME NUMBER(18,0) NULL,
  HIS_CREATOR VARCHAR2(100) NULL,
  HIS_MODIFIER VARCHAR2(100) NULL,
  
  -- Working State
  WORKING_STATE_ID VARCHAR2(36) NULL
);

-- Create indexes for EXP_EXP_MEST_OTHER
CREATE INDEX IDX_EXP_MEST_OTHER_CODE ON EXP_EXP_MEST_OTHER(EXP_MEST_CODE);
CREATE INDEX IDX_EXP_MEST_OTHER_DATE ON EXP_EXP_MEST_OTHER(CREATE_DATE);
CREATE INDEX IDX_EXP_MEST_OTHER_WORKING_STATE ON EXP_EXP_MEST_OTHER(WORKING_STATE_ID);

-- Comments for EXP_EXP_MEST_OTHER
COMMENT ON TABLE EXP_EXP_MEST_OTHER IS 'Other export medicine records from HIS GetView2';
COMMENT ON COLUMN EXP_EXP_MEST_OTHER.HIS_EXP_MEST_ID IS 'Primary key from HIS system (ID from GetView2)';
COMMENT ON COLUMN EXP_EXP_MEST_OTHER.WORKING_STATE_ID IS 'Reference to MST_EXPORT_STATUS.id (working_state)';

-- Create EXP_EXP_MEST_OTHER_MED table (Medicine details from GetView1)
CREATE TABLE EXP_EXP_MEST_OTHER_MED (
  ID VARCHAR2(36) NOT NULL PRIMARY KEY,
  CREATE_TIME NUMBER(19,0) NOT NULL,
  MODIFY_TIME NUMBER(19,0) NOT NULL,
  CREATOR VARCHAR2(100) NULL,
  MODIFIER VARCHAR2(100) NULL,
  IS_ACTIVE NUMBER(1,0) DEFAULT 1 NOT NULL,
  IS_DELETE NUMBER(1,0) DEFAULT 0 NOT NULL,
  
  -- Primary Key từ HIS
  HIS_ID NUMBER(19,0) NOT NULL UNIQUE,
  
  -- Foreign Keys
  EXP_MEST_ID NUMBER(19,0) NOT NULL,
  EXP_MEST_LOCAL_ID VARCHAR2(36) NULL,
  
  -- Medicine Info
  MEDICINE_ID NUMBER(19,0) NULL,
  TDL_MEDI_STOCK_ID NUMBER(19,0) NULL,
  TDL_MEDICINE_TYPE_ID NUMBER(19,0) NULL,
  EXP_MEST_METY_REQ_ID NUMBER(19,0) NULL,
  CK_IMP_MEST_MEDICINE_ID NUMBER(19,0) NULL,
  
  -- Export Info
  IS_EXPORT NUMBER(1,0) NULL,
  AMOUNT NUMBER(18,2) NULL,
  EXPORT_AMOUNT NUMBER(18,2) NULL,
  EXPORT_BY_USER VARCHAR2(36) NULL,
  EXPORT_TIME NUMBER(19,0) NULL,
  ACTUAL_EXP_AMOUNT NUMBER(18,2) NULL,
  ACTUAL_EXP_BY_USER VARCHAR2(36) NULL,
  ACTUAL_EXP_TIME NUMBER(19,0) NULL,
  
  -- Approval Info
  APPROVAL_LOGINNAME VARCHAR2(100) NULL,
  APPROVAL_USERNAME VARCHAR2(500) NULL,
  APPROVAL_TIME NUMBER(19,0) NULL,
  APPROVAL_DATE NUMBER(19,0) NULL,
  
  -- Export User Info
  EXP_LOGINNAME VARCHAR2(100) NULL,
  EXP_USERNAME VARCHAR2(500) NULL,
  EXP_TIME NUMBER(19,0) NULL,
  EXP_DATE NUMBER(19,0) NULL,
  
  -- Denormalized ExpMest Info
  EXP_MEST_CODE VARCHAR2(50) NULL,
  MEDI_STOCK_ID NUMBER(19,0) NULL,
  EXP_MEST_STT_ID NUMBER(19,0) NULL,
  
  -- Price Info
  IMP_PRICE NUMBER(18,2) NULL,
  IMP_VAT_RATIO NUMBER(18,2) NULL,
  PRICE NUMBER(18,2) NULL,
  VAT_RATIO NUMBER(18,2) NULL,
  VIR_PRICE NUMBER(18,2) NULL,
  TAX_RATIO NUMBER(18,2) NULL,
  
  -- Bid/Package Info
  BID_ID NUMBER(19,0) NULL,
  PACKAGE_NUMBER VARCHAR2(100) NULL,
  EXPIRED_DATE NUMBER(19,0) NULL,
  TDL_BID_GROUP_CODE VARCHAR2(50) NULL,
  TDL_BID_PACKAGE_CODE VARCHAR2(50) NULL,
  BID_NUMBER VARCHAR2(100) NULL,
  BID_NAME VARCHAR2(500) NULL,
  
  -- Medicine Type Info
  MEDICINE_TYPE_ID NUMBER(19,0) NULL,
  MEDICINE_TYPE_CODE VARCHAR2(50) NULL,
  MEDICINE_TYPE_NAME VARCHAR2(500) NULL,
  
  -- Import Info
  IMP_TIME NUMBER(19,0) NULL,
  SUPPLIER_ID NUMBER(19,0) NULL,
  SUPPLIER_CODE VARCHAR2(50) NULL,
  SUPPLIER_NAME VARCHAR2(500) NULL,
  
  -- Medicine Details
  MEDICINE_BYT_NUM_ORDER VARCHAR2(100) NULL,
  MEDICINE_REGISTER_NUMBER VARCHAR2(100) NULL,
  ACTIVE_INGR_BHYT_CODE VARCHAR2(100) NULL,
  ACTIVE_INGR_BHYT_NAME VARCHAR2(500) NULL,
  CONCENTRA VARCHAR2(200) NULL,
  MATERIAL_NUM_ORDER NUMBER(10,0) NULL,
  
  -- Service Info
  SERVICE_ID NUMBER(19,0) NULL,
  NATIONAL_NAME VARCHAR2(200) NULL,
  MANUFACTURER_ID NUMBER(19,0) NULL,
  MANUFACTURER_CODE VARCHAR2(50) NULL,
  MANUFACTURER_NAME VARCHAR2(500) NULL,
  BYT_NUM_ORDER VARCHAR2(100) NULL,
  REGISTER_NUMBER VARCHAR2(100) NULL,
  MEDICINE_GROUP_ID NUMBER(19,0) NULL,
  MEDICINE_GROUP_CODE VARCHAR2(10) NULL,
  MEDICINE_GROUP_NAME VARCHAR2(200) NULL,
  MEDICINE_GROUP_NUM_ORDER NUMBER(10,0) NULL,
  
  -- Unit Info
  SERVICE_UNIT_ID NUMBER(19,0) NULL,
  SERVICE_UNIT_CODE VARCHAR2(50) NULL,
  SERVICE_UNIT_NAME VARCHAR2(200) NULL,
  MEDICINE_NUM_ORDER NUMBER(10,0) NULL,
  
  -- Use Form Info
  MEDICINE_USE_FORM_ID NUMBER(19,0) NULL,
  MEDICINE_USE_FORM_CODE VARCHAR2(50) NULL,
  MEDICINE_USE_FORM_NAME VARCHAR2(200) NULL,
  MEDICINE_USE_FORM_NUM_ORDER NUMBER(10,0) NULL,
  
  -- Stock Info
  SUM_IN_STOCK NUMBER(18,2) NULL,
  SUM_BY_MEDICINE_IN_STOCK NUMBER(18,2) NULL,
  MEDI_STOCK_CODE VARCHAR2(50) NULL,
  MEDI_STOCK_NAME VARCHAR2(500) NULL,
  
  -- Order & Amount Info
  NUM_ORDER NUMBER(10,0) NULL,
  PRES_AMOUNT NUMBER(18,2) NULL,
  
  -- Patient & Treatment Info
  PATIENT_TYPE_ID NUMBER(19,0) NULL,
  PATIENT_TYPE_CODE VARCHAR2(10) NULL,
  PATIENT_TYPE_NAME VARCHAR2(200) NULL,
  TDL_PATIENT_ID NUMBER(19,0) NULL,
  TDL_TREATMENT_ID NUMBER(19,0) NULL,
  TDL_SERVICE_REQ_ID NUMBER(19,0) NULL,
  
  -- Instruction & Tutorial
  USE_TIME_TO NUMBER(19,0) NULL,
  TUTORIAL VARCHAR2(2000) NULL,
  TDL_INTRUCTION_TIME NUMBER(19,0) NULL,
  TDL_INTRUCTION_DATE NUMBER(19,0) NULL,
  HTU_TEXT VARCHAR2(200) NULL,
  
  -- Dosage Info
  MORNING VARCHAR2(10) NULL,
  EVENING VARCHAR2(10) NULL,
  
  -- ExpMest Denormalized Info
  EXP_MEST_TYPE_ID NUMBER(19,0) NULL,
  TDL_AGGR_EXP_MEST_ID NUMBER(19,0) NULL,
  AGGR_EXP_MEST_ID NUMBER(19,0) NULL,
  REQ_ROOM_ID NUMBER(19,0) NULL,
  REQ_DEPARTMENT_ID NUMBER(19,0) NULL,
  REQ_USER_TITLE VARCHAR2(200) NULL,
  REQ_LOGINNAME VARCHAR2(100) NULL,
  REQ_USERNAME VARCHAR2(500) NULL,
  
  -- Medicine Line
  MEDICINE_LINE_ID NUMBER(19,0) NULL
);

-- Create indexes for EXP_EXP_MEST_OTHER_MED
CREATE INDEX IDX_EXP_MEST_OTHER_MED_EXP_ID ON EXP_EXP_MEST_OTHER_MED(EXP_MEST_ID);
CREATE INDEX IDX_EXP_MEST_OTHER_MED_LOCAL_ID ON EXP_EXP_MEST_OTHER_MED(EXP_MEST_LOCAL_ID);
CREATE INDEX IDX_EXP_MEST_OTHER_MED_MED_ID ON EXP_EXP_MEST_OTHER_MED(MEDICINE_ID);
CREATE INDEX IDX_EXP_MEST_OTHER_MED_STOCK ON EXP_EXP_MEST_OTHER_MED(MEDI_STOCK_ID);

-- Comments for EXP_EXP_MEST_OTHER_MED
COMMENT ON TABLE EXP_EXP_MEST_OTHER_MED IS 'Medicine details for other export medicine records from HIS GetView1';
COMMENT ON COLUMN EXP_EXP_MEST_OTHER_MED.HIS_ID IS 'Primary key from HIS system (ID from GetView1)';
COMMENT ON COLUMN EXP_EXP_MEST_OTHER_MED.EXP_MEST_ID IS 'Reference to EXP_EXP_MEST_OTHER.HIS_EXP_MEST_ID (HIS ID)';
COMMENT ON COLUMN EXP_EXP_MEST_OTHER_MED.EXP_MEST_LOCAL_ID IS 'Reference to EXP_EXP_MEST_OTHER.ID (UUID) for faster local joins';

