-- Check endpoints with custom actions that might be incorrect
-- These endpoints should have specific actions, not generic CRUD

-- Check sync endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/sync%'
ORDER BY PATH, METHOD;

-- Check export endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/export%'
ORDER BY PATH, METHOD;

-- Check actual-export endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/actual-export%'
ORDER BY PATH, METHOD;

-- Check assign/revoke endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/assign%' OR PATH LIKE '%/revoke%'
ORDER BY PATH, METHOD;

-- Check reload endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/reload%'
ORDER BY PATH, METHOD;

-- Check summary endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/summary%'
ORDER BY PATH, METHOD;

-- Check count endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/count%'
ORDER BY PATH, METHOD;

-- Check /me endpoints
SELECT PATH, METHOD, RESOURCE_NAME, ACTION, IS_PUBLIC
FROM GW_API_ENDPOINTS
WHERE PATH LIKE '%/me%'
ORDER BY PATH, METHOD;

-- Summary: Count endpoints by action type
SELECT 
    ACTION,
    COUNT(*) AS COUNT
FROM GW_API_ENDPOINTS
WHERE IS_ACTIVE = 1
GROUP BY ACTION
ORDER BY COUNT(*) DESC;
