-- Gateway Config Service - Database Migration Script
-- Creates tables for API endpoint management and Kong synchronization

-- Table 1: GW_API_ENDPOINTS
-- Stores API endpoint configurations
CREATE TABLE GW_API_ENDPOINTS (
    ID VARCHAR2(36) PRIMARY KEY,
    PATH VARCHAR2(500) NOT NULL,
    METHOD VARCHAR2(10) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    MODULE VARCHAR2(100),
    IS_PUBLIC NUMBER(1) DEFAULT 0,
    RATE_LIMIT_REQUESTS NUMBER(10),
    RATE_LIMIT_WINDOW VARCHAR2(10),
    KONG_ROUTE_ID VARCHAR2(100),
    KONG_ROUTE_NAME VARCHAR2(200),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(36),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP(6),
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_GW_PATH_METHOD UNIQUE (PATH, METHOD)
);

-- Indexes for GW_API_ENDPOINTS
CREATE INDEX IDX_GW_ENDPOINTS_MODULE ON GW_API_ENDPOINTS(MODULE);
CREATE INDEX IDX_GW_ENDPOINTS_ACTIVE ON GW_API_ENDPOINTS(IS_ACTIVE);
CREATE INDEX IDX_GW_ENDPOINTS_KONG_ID ON GW_API_ENDPOINTS(KONG_ROUTE_ID);

-- Table 2: GW_API_ENDPOINT_ROLES
-- Maps API endpoints to allowed roles (Many-to-Many)
CREATE TABLE GW_API_ENDPOINT_ROLES (
    ID VARCHAR2(36) PRIMARY KEY,
    ENDPOINT_ID VARCHAR2(36) NOT NULL,
    ROLE_CODE VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(36),
    CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR2(36),
    UPDATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP(6),
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_GW_ENDPOINT FOREIGN KEY (ENDPOINT_ID) 
        REFERENCES GW_API_ENDPOINTS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_GW_ROLE FOREIGN KEY (ROLE_CODE) 
        REFERENCES USR_ROLES(CODE) ON DELETE CASCADE,
    CONSTRAINT UQ_GW_ENDPOINT_ROLE UNIQUE (ENDPOINT_ID, ROLE_CODE)
);

-- Indexes for GW_API_ENDPOINT_ROLES
CREATE INDEX IDX_GW_ENDPOINT_ROLES_EP ON GW_API_ENDPOINT_ROLES(ENDPOINT_ID);
CREATE INDEX IDX_GW_ENDPOINT_ROLES_ROLE ON GW_API_ENDPOINT_ROLES(ROLE_CODE);

-- Sample data: Public endpoints (no authentication required)
INSERT INTO GW_API_ENDPOINTS (ID, PATH, METHOD, DESCRIPTION, MODULE, IS_PUBLIC, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), '/api/auth/login', 'POST', 'User login endpoint', 'auth', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO GW_API_ENDPOINTS (ID, PATH, METHOD, DESCRIPTION, MODULE, IS_PUBLIC, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
VALUES (SYS_GUID(), '/api/auth/refresh', 'POST', 'Refresh access token', 'auth', 1, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Sample data: Protected endpoints (require authentication + specific roles)
DECLARE
    v_endpoint_id VARCHAR2(36);
BEGIN
    -- Inventory ExpMest endpoint (ADMIN + DOCTOR)
    v_endpoint_id := SYS_GUID();
    INSERT INTO GW_API_ENDPOINTS (ID, PATH, METHOD, DESCRIPTION, MODULE, IS_PUBLIC, RATE_LIMIT_REQUESTS, RATE_LIMIT_WINDOW, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
    VALUES (v_endpoint_id, '/api/inventory/exp-mests', 'GET', 'Get ExpMest list', 'inventory', 0, 100, '1m', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    
    INSERT INTO GW_API_ENDPOINT_ROLES (ID, ENDPOINT_ID, ROLE_CODE, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
    VALUES (SYS_GUID(), v_endpoint_id, 'ADMIN', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    
    INSERT INTO GW_API_ENDPOINT_ROLES (ID, ENDPOINT_ID, ROLE_CODE, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
    VALUES (SYS_GUID(), v_endpoint_id, 'DOCTOR', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    
    -- Role management endpoint (ADMIN only)
    v_endpoint_id := SYS_GUID();
    INSERT INTO GW_API_ENDPOINTS (ID, PATH, METHOD, DESCRIPTION, MODULE, IS_PUBLIC, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
    VALUES (v_endpoint_id, '/api/roles', 'GET', 'Get all roles', 'users', 0, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    
    INSERT INTO GW_API_ENDPOINT_ROLES (ID, ENDPOINT_ID, ROLE_CODE, IS_ACTIVE, VERSION, CREATED_AT, UPDATED_AT)
    VALUES (SYS_GUID(), v_endpoint_id, 'ADMIN', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    
    COMMIT;
END;
/

-- Comments for documentation
COMMENT ON TABLE GW_API_ENDPOINTS IS 'Stores API endpoint configurations for dynamic Kong Gateway management';
COMMENT ON TABLE GW_API_ENDPOINT_ROLES IS 'Maps API endpoints to allowed roles for fine-grained access control';

COMMENT ON COLUMN GW_API_ENDPOINTS.PATH IS 'API endpoint path (e.g., /api/users/profile)';
COMMENT ON COLUMN GW_API_ENDPOINTS.METHOD IS 'HTTP method (GET, POST, PUT, DELETE, PATCH)';
COMMENT ON COLUMN GW_API_ENDPOINTS.IS_PUBLIC IS '1 = Public (no auth), 0 = Protected (requires JWT)';
COMMENT ON COLUMN GW_API_ENDPOINTS.RATE_LIMIT_REQUESTS IS 'Number of requests allowed per window';
COMMENT ON COLUMN GW_API_ENDPOINTS.RATE_LIMIT_WINDOW IS 'Time window for rate limiting (e.g., 1m, 1h, 1d)';
COMMENT ON COLUMN GW_API_ENDPOINTS.KONG_ROUTE_ID IS 'Kong route ID (populated after sync)';
COMMENT ON COLUMN GW_API_ENDPOINTS.KONG_ROUTE_NAME IS 'Kong route name (populated after sync)';
