-- File: queries/external-db/his-employee.query.sql
-- Description: Get employee information from HIS_EMPLOYEE table
-- Parameters: :USER_NAME (required) - Login name of the employee
-- Returns: ID (ACS_ID), LOGINNAME (USER_NAME), DIPLOMA, IS_DOCTOR, IS_ADMIN, DEPARTMENT_ID, 
--          DEFAULT_MEDI_STOCK_IDS, IS_NURSE, DOB, TITLE, MAX_SERVICE_REQ_PER_DAY, 
--          TDL_USERNAME, TDL_EMAIL, TDL_MOBILE, SOCIAL_INSURANCE_NUMBER, 
--          DO_NOT_ALLOW_SIMULTANEITY, GENDER_ID, ETHNIC_CODE, DIPLOMA_DATE, 
--          DIPLOMA_PLACE, IDENTIFICATION_NUMBER, BRANCH_ID, CAREER_TITLE_ID

SELECT 
  ID AS ACS_ID,
  LOGINNAME AS USER_NAME,
  DIPLOMA,
  IS_DOCTOR,
  IS_ADMIN,
  DEPARTMENT_ID,
  DEFAULT_MEDI_STOCK_IDS,
  IS_NURSE,
  DOB,
  TITLE,
  MAX_SERVICE_REQ_PER_DAY,
  TDL_USERNAME,
  TDL_EMAIL,
  TDL_MOBILE,
  SOCIAL_INSURANCE_NUMBER,
  DO_NOT_ALLOW_SIMULTANEITY,
  GENDER_ID,
  ETHNIC_CODE,
  DIPLOMA_DATE,
  DIPLOMA_PLACE,
  IDENTIFICATION_NUMBER,
  BRANCH_ID,
  CAREER_TITLE_ID
FROM HIS_EMPLOYEE
WHERE LOGINNAME = :USER_NAME

